/*calcular novo salário*/

SET SERVEROUTPUT ON;

DECLARE
 V_SALARIO FLOAT;
 V_DIFERENCA FLOAT;
BEGIN
  V_SALARIO := 1101.95;
  V_DIFERENCA := 1101.95*0.08;
  V_SALARIO := SALARIO+DIFERENCA;
  
  DBMS_OUTPUT.PUT_LINE (V_SALARIO);
END;